name: nest

on:
  push:
    branches:
      - master
      - test_branch
jobs:
  curl-jenkins-job:
    name: "Build"
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: self-hosted
    steps:
      - name: "Call build job"
        uses: indiesdev/curl@v1.1
        with:
          url: "http://${{ secrets.JENKINS }}@34.80.82.174:8080/job/build/job/nestjs/buildWithParameters?token=github&branch=master&env=prod"
          method: "POST"

  curl-jenkins-job-build-deploy-dev:
    name: "Pipeline"
    if: ${{ github.ref == 'refs/heads/test_branch' }}
    runs-on: self-hosted
    steps:
      - name: "Call jenkins pipeline job"
        uses: indiesdev/curl@v1.1
        with:
          url: "http://${{ secrets.JENKINS }}@34.80.82.174:8080/job/pipeline/job/nestjs/buildWithParameters?token=github&branch=test_branch&environment=dev"
          method: "POST"